#define INST_ADDR_START 0
#define USRSYS_STACK_START	0x00100000 //User & Sys mode
#define SVC_STACK_START	0x00300000 //Supervisor mode
#define IRQ_STACK_START	0x00400000 //Interrupt Request mode
#define FIQ_STACK_START	0x00500000 //Fast Interrupt Request mode
#define ABT_STACK_START	0x00600000 //Abort mode
#define UND_STACK_START	0x00700000 //Undefined mode
#define TASK_STACK_START	0x00800000 //task stack 
#define GLOBAL_STACK_START	0x04800000 //glboal stack 
#define DALLOC_STACK_START	0x04900000 //Dynamically allocated stack

#define INST_MEM_SIZE		(USRSYS_STACK_START - INST_ADDR_START)
#define USRSYS_STACK_SIZE	(SVC_STACK_START - USRSYS_STACK_START)
#define SVC_STACK_SIZE	(IRQ_STACK_START - SVC_STACK_START)
#define IRQ_STACK_SIZE	(FIQ_STACK_START - IRQ_STACK_START)
#define FIQ_STACK_SIZE	(ABT_STACK_START - FIQ_STACK_START)
#define ABT_STACK_SIZE	(UND_STACK_START - ABT_STACK_START)
#define UND_STACK_SIZE	(TASK_STACK_START - UND_STACK_START)
#define TASK_STACK_SIZE	(GLOBAL_STACK_START - TASK_STACK_START)
#define GLOBAL_STACK_SIZE	(DALLOC_STACK_START - GLOBAL_STACK_START)
#define DALLOC_STACK_SIZE	(55 * 1024 * 1024) //55 MB 

#define USRSYS_STACK_TOP	(USRSYS_STACK_START + USRSYS_STACK_SIZE - 4)
#define SVC_STACK_TOP		(SVC_STACK_START + SVC_STACK_SIZE - 4)
#define IRQ_STACK_TOP		(IRQ_STACK_START + IRQ_STACK_SIZE - 4)
#define FIQ_STACK_TOP		(FIQ_STACK_START + FIQ_STACK_SIZE - 4)
#define ABT_STACK_TOP		(ABT_STACK_START + ABT_STACK_SIZE - 4)
#define UND_STACK_TOP		(UND_STACK_START + UND_STACK_SIZE - 4)

